### PR TITLE
locked windows installation location

### LINKED ISSUE #9: Windows installer: Remove ability to chose the base directory
As VST3 has a fixed install location, this dialog confuses people 

Reported on [gearslutz.com](https://www.gearslutz.com/board/new-product-alert/1332352-free-amp-open-source-overdrive-vst-au.html). Will be fixed with the next release

### PR DESCRIPTION
**Pull request by moritzsur**

### CODE REVIEW

**Comment by JanosGit** [comment]
Ah great, this solves https://github.com/JanosGit/Schrammel_OJD/issues/9 I guess?

**Comment by JanosGit** [comment]
I changed the destination branch to develop. I see that you however checked in a vst3 build artifact. Could you please remove that again? I'd squash and merge your changes then

**Comment by moritzsur** [comment]
My fault! Yes it solves #9

**Comment by JanosGit** [comment]
Thank you for your contribution

**Pull request merged**
